#pragma once

#define WORLDEDITOR_METHOD_SETGAMEPATH			("SetGamePath")
#define WORLDEDITOR_METHOD_SETMAP				("SetMap")
#define WORLDEDITOR_METHOD_CREATEACTOR			("CreateActor")
#define WORLDEDITOR_METHOD_SETACTORBASEMODELID	("SetActorBaseModelId")
#define WORLDEDITOR_METHOD_SETACTORTOPMODELID	("SetActorTopModelId")
#define WORLDEDITOR_METHOD_SETACTORPOSITION		("SetActorPosition")
#define WORLDEDITOR_METHOD_SETCONTROLSCHEME		("SetControlScheme")
#define WORLDEDITOR_METHOD_GETCAMERAPOSITION	("GetCameraPosition")
#define WORLDEDITOR_METHOD_SETCAMERAPOSITION	("SetCameraPosition")

#define WORLDEDITOR_PARAM_RESULT				("Result")
#define WORLDEDITOR_PARAM_ID					("Id")
#define WORLDEDITOR_PARAM_PATH					("Path")
#define WORLDEDITOR_PARAM_POSITION				("Position")
#define WORLDEDITOR_PARAM_CONTROLSCHEME			("ControlScheme")
#define WORLDEDITOR_PARAM_MAPID					("MapId")
#define WORLDEDITOR_PARAM_BASEMODELID			("BaseModelId")
#define WORLDEDITOR_PARAM_TOPMODELID			("TopModelId")

#define WORLDEDITOR_CONTROLSCHEME_VIEWER		1
#define WORLDEDITOR_CONTROLSCHEME_EDITOR		2

#define WORLDEDITOR_RESULT_SUCCEEDED			("success")
#define WORLDEDITOR_RESULT_FAILED				("failed")
